/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : RxBuf2.c
**     Project     : FRDM_HelloWorld
**     Processor   : MKL25Z128VLK4
**     Component   : RingBufferUInt8
**     Version     : Component 01.003, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-12-01, 23:39, # CodeGen: 3
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Put             - byte RxBuf2_Put(byte elem);
**         Get             - byte RxBuf2_Get(byte *elemP);
**         NofElements     - byte RxBuf2_NofElements(void);
**         NofFreeElements - byte RxBuf2_NofFreeElements(void);
**         Init            - void RxBuf2_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file RxBuf2.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup RxBuf2_module RxBuf2 module documentation
**  @{
*/         

/* MODULE RxBuf2. */

#include "RxBuf2.h"

static uint8_t RxBuf2_buffer[RxBuf2_BUF_SIZE]; /* ring buffer */
static uint8_t RxBuf2_inIdx;  /* input index */
static uint8_t RxBuf2_outIdx; /* output index */
static uint8_t RxBuf2_inSize; /* size of input data */
/*
** ===================================================================
**     Method      :  RxBuf2_Put (component RingBufferUInt8)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte RxBuf2_Put(byte elem)
{
  byte res = ERR_OK;

  EnterCritical();
  if (RxBuf2_inSize==RxBuf2_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    RxBuf2_buffer[RxBuf2_inIdx] = elem;
    RxBuf2_inSize++;
    RxBuf2_inIdx++;
    if (RxBuf2_inIdx==RxBuf2_BUF_SIZE) {
      RxBuf2_inIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  RxBuf2_Get (component RingBufferUInt8)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte RxBuf2_Get(byte *elemP)
{
  byte res = ERR_OK;

  EnterCritical();
  if (RxBuf2_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = RxBuf2_buffer[RxBuf2_outIdx];
    RxBuf2_inSize--;
    RxBuf2_outIdx++;
    if (RxBuf2_outIdx==RxBuf2_BUF_SIZE) {
      RxBuf2_outIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  RxBuf2_NofElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte RxBuf2_NofElements(void)
{
  return RxBuf2_inSize;
}

/*
** ===================================================================
**     Method      :  RxBuf2_NofFreeElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte RxBuf2_NofFreeElements(void)
{
  return (byte)(RxBuf2_BUF_SIZE-RxBuf2_inSize);
}

/*
** ===================================================================
**     Method      :  RxBuf2_Init (component RingBufferUInt8)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void RxBuf2_Init(void)
{
  RxBuf2_inIdx = 0;
  RxBuf2_outIdx = 0;
  RxBuf2_inSize = 0;
}

/* END RxBuf2. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
